magic_v2:
	rm -rf magic_square_v2.pml.trail
	spin -a magic_square_v2.pml
	gcc pan.c -o pan
	./pan
# check counterexample:
	spin -t magic_square_v2.pml

magic_v3:
	rm -rf magic_square_v3.pml.trail
	spin -a magic_square_v3.pml
	gcc pan.c -o pan
	./pan
# check counterexample:
	spin -t magic_square_v3.pml
