hanoi:
	spin -a hanoi.pml
	gcc pan.c -o pan
	./pan -i
# check counterexample:
	spin -t hanoi.pml

peterson:
	spin -a peterson.pml
	gcc pan.c -o pan
	./pan -f -a
# no counterexample:
# 	spin -t peterson.pml

missionary:
	spin -a missionary.pml
	gcc pan.c -o pan
	./pan -i
# check counterexample:
	spin -t missionary.pml
